# Generated by Django 3.1.3 on 2020-12-07 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0002_auto_20201207_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='report',
            field=models.FileField(blank=True, null=True, upload_to='static/project/report'),
        ),
    ]
