# Generated by Django 3.1.3 on 2020-12-07 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0003_auto_20201207_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='git_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='youtube_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
