# Generated by Django 3.1.3 on 2020-12-08 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0005_auto_20201207_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='completed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='team',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='git_link',
            field=models.URLField(blank=True, null=True, verbose_name='Project Files'),
        ),
    ]
