# Generated by Django 3.1.3 on 2020-12-08 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialaccount', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialaccount',
            name='registration_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
