# Generated by Django 3.1.3 on 2020-12-06 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Universities', '0001_initial'),
        ('socialaccount', '0003_extra_data_default_dict'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialaccount',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Universities.batches'),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='contact',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Universities.departments'),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Universities.universities'),
        ),
    ]
